/* export const moodsArray = [
    "hip-hop",
    "pop",
    "moody",
    "dance/electronic",
    "charts",
    "rock",
    "skate noise",
    "chillout",
    "daily drive",
    "fresh finds",
    "equal",
    "schlager",
    "mixed by",
    "fitness",
    "k-pop",
    "sleeping",
    "party",
    "at home",
    "ambient",
    "rnb",
    "love",
    "kids & family",
    "soccer",
    "metal",
    "classic",
    "jazz",
    "folk & acustic",
    "country",
    "disney",
    "nature & white noise",
    "soul",
    "gaming",
    "glow",
    "tv & films",
    "netflix",
    "instrumental",
    "wellness",
    "blues",
    "cooking",
    "alternative",
    "travel",
    "reggae",
    "caribics",
    "afro",
    "funk",
    "avant-garde & Experimental",
    "blues",
    "country",
    "easy listening",
    "electronic",

];
 */